image: registry.gitlab.com/huntears/light-epitest/master:latest

build-job:
  stage: build
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j2
    - cpack -C release
  artifacts:
    when: on_success
    paths:
      - build/liskvork-*.rpm
      - build/liskvork-*.deb

test-job:
  stage: test
  script:
    - cd build
    - ./unit_tests
  needs: ["build-job"]
