image: registry.gitlab.com/huntears/light-epitest/master:latest

build-job:
  stage: build
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j6
    - cpack -C release
  artifacts:
    when: on_success
    paths:
      - build
    expire_in: 1 week

test-job:
  stage: test
  script:
    - cd build
    - ./unit_tests
  dependencies:
    - build-job
